#############################################################################
# Makefile for building: GroundStation.app/Contents/MacOS/GroundStation
# Generated by qmake (2.01a) (Qt 4.7.4) on: Sat Sep 17 15:46:13 2011
# Project:  GroundStation.pro
# Template: app
# Command: /Users/elendal/QtSDK/Desktop/Qt/474/gcc/bin/qmake -spec ../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/macx-g++ -o Makefile GroundStation.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/macx-g++ -I. -I../../../QtSDK/Desktop/Qt/474/gcc/lib/QtCore.framework/Versions/4/Headers -I../../../QtSDK/Desktop/Qt/474/gcc/include/QtCore -I../../../QtSDK/Desktop/Qt/474/gcc/lib/QtGui.framework/Versions/4/Headers -I../../../QtSDK/Desktop/Qt/474/gcc/include/QtGui -I../../../QtSDK/Desktop/Qt/474/gcc/lib/QtOpenGL.framework/Versions/4/Headers -I../../../QtSDK/Desktop/Qt/474/gcc/include/QtOpenGL -I../../../QtSDK/Desktop/Qt/474/gcc/include -I. -Isrc -Isrc/thrift -Isrc/sensors -Isrc/ui -Isrc/kalman -I/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/System/Library/Frameworks/AGL.framework/Headers -I. -F/Users/elendal/QtSDK/Desktop/Qt/474/gcc/lib
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/Users/elendal/QtSDK/Desktop/Qt/474/gcc/lib -L/Users/elendal/QtSDK/Desktop/Qt/474/gcc/lib -framework QtOpenGL -framework QtGui -framework QtCore -framework OpenGL -framework AGL 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Users/elendal/QtSDK/Desktop/Qt/474/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/Calibrator.cpp \
		src/DataLogger.cpp \
		src/Geo.cpp \
		src/GroundStation.cpp \
		src/LatLon.cpp \
		src/SensorReader.cpp \
		src/sensors/Accelerometer.cpp \
		src/sensors/Compass.cpp \
		src/sensors/Estimator.cpp \
		src/sensors/Gyroscope.cpp \
		src/sensors/Vector.cpp \
		src/thrift/Protocol.cpp \
		src/thrift/SerialTransport.cpp \
		src/ui/GroundControlWindow.cpp \
		src/ui/CompassWidget.cpp \
		src/ui/SensorThread.cpp \
		src/kalman/kstatics.cpp moc_GroundControlWindow.cpp \
		moc_CompassWidget.cpp \
		moc_SensorThread.cpp
OBJECTS       = Calibrator.o \
		DataLogger.o \
		Geo.o \
		GroundStation.o \
		LatLon.o \
		SensorReader.o \
		Accelerometer.o \
		Compass.o \
		Estimator.o \
		Gyroscope.o \
		Vector.o \
		Protocol.o \
		SerialTransport.o \
		GroundControlWindow.o \
		CompassWidget.o \
		SensorThread.o \
		kstatics.o \
		moc_GroundControlWindow.o \
		moc_CompassWidget.o \
		moc_SensorThread.o
DIST          = ../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac.conf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac-g++.conf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_pre.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/dwarf2.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/debug.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_post.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/x86_64.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/objective_c.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/opengl.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/rez.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/sdk.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf \
		GroundStation.pro
QMAKE_TARGET  = GroundStation
DESTDIR       = 
TARGET        = GroundStation.app/Contents/MacOS/GroundStation

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile GroundStation.app/Contents/PkgInfo GroundStation.app/Contents/Resources/empty.lproj GroundStation.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) GroundStation.app/Contents/MacOS/ || $(MKDIR) GroundStation.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: GroundStation.pro  ../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/macx-g++/qmake.conf ../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac.conf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac-g++.conf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_pre.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/dwarf2.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/debug.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_post.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/x86_64.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/objective_c.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/opengl.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/rez.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/sdk.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf \
		../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec ../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/macx-g++ -o Makefile GroundStation.pro
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac.conf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac-g++.conf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_pre.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/dwarf2.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/debug.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_post.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/x86_64.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/objective_c.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/opengl.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/rez.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/sdk.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf:
../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec ../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/macx-g++ -o Makefile GroundStation.pro

GroundStation.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) GroundStation.app/Contents || $(MKDIR) GroundStation.app/Contents 
	@$(DEL_FILE) GroundStation.app/Contents/PkgInfo
	@echo "APPL????" >GroundStation.app/Contents/PkgInfo
GroundStation.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) GroundStation.app/Contents/Resources || $(MKDIR) GroundStation.app/Contents/Resources 
	@touch GroundStation.app/Contents/Resources/empty.lproj
	
GroundStation.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) GroundStation.app/Contents || $(MKDIR) GroundStation.app/Contents 
	@$(DEL_FILE) GroundStation.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,GroundStation,g" -e "s,@TYPEINFO@,????,g" ../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/macx-g++/Info.plist.app >GroundStation.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/GroundStation1.0.0 || $(MKDIR) .tmp/GroundStation1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/GroundStation1.0.0/ && $(COPY_FILE) --parents src/Calibrator.h src/crc16.h src/DataLogger.h src/Geo.h src/LatLon.h src/SensorReader.h src/sensors/Accelerometer.h src/sensors/Compass.h src/sensors/Estimator.h src/sensors/Gyroscope.h src/sensors/Vector.h src/thrift/fd_stream.h src/thrift/Protocol.h src/thrift/SerialTransport.h src/ui/GroundControlWindow.h src/ui/CompassWidget.h src/ui/SensorThread.h src/kalman/ktypes.hpp src/kalman/kvector_impl.hpp src/kalman/kvector.hpp src/kalman/ekfilter_impl.hpp src/kalman/ekfilter.hpp src/kalman/kfilter_impl.hpp src/kalman/kfilter.hpp src/kalman/kmatrix_impl.hpp src/kalman/kmatrix.hpp .tmp/GroundStation1.0.0/ && $(COPY_FILE) --parents src/Calibrator.cpp src/DataLogger.cpp src/Geo.cpp src/GroundStation.cpp src/LatLon.cpp src/SensorReader.cpp src/sensors/Accelerometer.cpp src/sensors/Compass.cpp src/sensors/Estimator.cpp src/sensors/Gyroscope.cpp src/sensors/Vector.cpp src/thrift/Protocol.cpp src/thrift/SerialTransport.cpp src/ui/GroundControlWindow.cpp src/ui/CompassWidget.cpp src/ui/SensorThread.cpp src/kalman/kstatics.cpp .tmp/GroundStation1.0.0/ && (cd `dirname .tmp/GroundStation1.0.0` && $(TAR) GroundStation1.0.0.tar GroundStation1.0.0 && $(COMPRESS) GroundStation1.0.0.tar) && $(MOVE) `dirname .tmp/GroundStation1.0.0`/GroundStation1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/GroundStation1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r GroundStation.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_GroundControlWindow.cpp moc_CompassWidget.cpp moc_SensorThread.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_GroundControlWindow.cpp moc_CompassWidget.cpp moc_SensorThread.cpp
moc_GroundControlWindow.cpp: src/ui/CompassWidget.h \
		src/ui/GroundControlWindow.h
	/Users/elendal/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/ui/GroundControlWindow.h -o moc_GroundControlWindow.cpp

moc_CompassWidget.cpp: src/ui/CompassWidget.h
	/Users/elendal/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/ui/CompassWidget.h -o moc_CompassWidget.cpp

moc_SensorThread.cpp: src/thrift/Protocol.h \
		src/thrift/SerialTransport.h \
		src/thrift/fd_stream.h \
		src/sensors/Compass.h \
		src/sensors/Vector.h \
		src/sensors/Accelerometer.h \
		src/sensors/Gyroscope.h \
		src/SensorReader.h \
		src/DataLogger.h \
		src/LatLon.h \
		src/ui/SensorThread.h
	/Users/elendal/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/ui/SensorThread.h -o moc_SensorThread.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

Calibrator.o: src/Calibrator.cpp src/Calibrator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Calibrator.o src/Calibrator.cpp

DataLogger.o: src/DataLogger.cpp src/DataLogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DataLogger.o src/DataLogger.cpp

Geo.o: src/Geo.cpp src/Geo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Geo.o src/Geo.cpp

GroundStation.o: src/GroundStation.cpp src/ui/GroundControlWindow.h \
		src/ui/CompassWidget.h \
		src/ui/SensorThread.h \
		src/thrift/Protocol.h \
		src/thrift/SerialTransport.h \
		src/thrift/fd_stream.h \
		src/sensors/Compass.h \
		src/sensors/Vector.h \
		src/sensors/Accelerometer.h \
		src/sensors/Gyroscope.h \
		src/SensorReader.h \
		src/DataLogger.h \
		src/LatLon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GroundStation.o src/GroundStation.cpp

LatLon.o: src/LatLon.cpp src/LatLon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LatLon.o src/LatLon.cpp

SensorReader.o: src/SensorReader.cpp src/SensorReader.h \
		src/thrift/Protocol.h \
		src/crc16.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SensorReader.o src/SensorReader.cpp

Accelerometer.o: src/sensors/Accelerometer.cpp src/sensors/Accelerometer.h \
		src/sensors/Estimator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Accelerometer.o src/sensors/Accelerometer.cpp

Compass.o: src/sensors/Compass.cpp src/sensors/Compass.h \
		src/sensors/Vector.h \
		src/sensors/Estimator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Compass.o src/sensors/Compass.cpp

Estimator.o: src/sensors/Estimator.cpp src/sensors/Estimator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Estimator.o src/sensors/Estimator.cpp

Gyroscope.o: src/sensors/Gyroscope.cpp src/sensors/Gyroscope.h \
		src/sensors/Estimator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Gyroscope.o src/sensors/Gyroscope.cpp

Vector.o: src/sensors/Vector.cpp src/sensors/Vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Vector.o src/sensors/Vector.cpp

Protocol.o: src/thrift/Protocol.cpp src/thrift/Protocol.h \
		src/thrift/SerialTransport.h \
		src/thrift/fd_stream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Protocol.o src/thrift/Protocol.cpp

SerialTransport.o: src/thrift/SerialTransport.cpp src/thrift/SerialTransport.h \
		src/thrift/fd_stream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SerialTransport.o src/thrift/SerialTransport.cpp

GroundControlWindow.o: src/ui/GroundControlWindow.cpp src/ui/GroundControlWindow.h \
		src/ui/CompassWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GroundControlWindow.o src/ui/GroundControlWindow.cpp

CompassWidget.o: src/ui/CompassWidget.cpp src/ui/CompassWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CompassWidget.o src/ui/CompassWidget.cpp

SensorThread.o: src/ui/SensorThread.cpp src/ui/SensorThread.h \
		src/thrift/Protocol.h \
		src/thrift/SerialTransport.h \
		src/thrift/fd_stream.h \
		src/sensors/Compass.h \
		src/sensors/Vector.h \
		src/sensors/Accelerometer.h \
		src/sensors/Gyroscope.h \
		src/SensorReader.h \
		src/DataLogger.h \
		src/LatLon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SensorThread.o src/ui/SensorThread.cpp

kstatics.o: src/kalman/kstatics.cpp src/kalman/kvector.hpp \
		src/kalman/ktypes.hpp \
		src/kalman/kvector_impl.hpp \
		src/kalman/kmatrix.hpp \
		src/kalman/kmatrix_impl.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kstatics.o src/kalman/kstatics.cpp

moc_GroundControlWindow.o: moc_GroundControlWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GroundControlWindow.o moc_GroundControlWindow.cpp

moc_CompassWidget.o: moc_CompassWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CompassWidget.o moc_CompassWidget.cpp

moc_SensorThread.o: moc_SensorThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SensorThread.o moc_SensorThread.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

